openapi: 3.0.3
info:
  title: Messenger API
  version: 1.0.0
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        avatar:
          type: string
          format: uri

paths:
  /authenticate:
    get:
      summary: Authenticate user
      description: Returns user information and authentication token if authentication is successful
      parameters:
        - in: query
          name: username
          description: User's username
          required: true
          schema:
            type: string
        - in: query
          name: password
          description: User's password
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                    description: User's username
                  firstName:
                    type: string
                    description: User's first name
                  lastName:
                    type: string
                    description: User's last name
                  avatar:
                    type: string
                    format: uri
                  token:
                    type: string
                    description: Authentication token
        '400':
          description: Bad request
        '404':
          description: User not found
  /register:
    post:
      summary: Register user
      description: Creates a new user account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf: [$ref: '#/components/schemas/User']
              required:
                - username
                - firstName
                - lastName
                - password
      responses:
        '201':
          description: User registration successful
        '400':
          description: Bad request
        '409':
          description: User already exists
  /users/{username}:
    post:
      summary: Update user information
      description: Update user information for a given username
      parameters:
        - in: path
          name: username
          description: User's username
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username
                firstName:
                  type: string
                  description: User's first name
                lastName:
                  type: string
                  description: User's last name
                password:
                  type: string
                  description: User's password
              required:
                - username
      responses:
        '200':
          description: User information updated successfully
          content:
            application/json:
              schema:
                allOf: [$ref: '#/components/schemas/User']
        '400':
          description: Bad request
        '401':
          description: Invalid token
        '409':
          description: Username already exists
      security:
        - bearerAuth: []
  /users:
    get:
      summary: Retrieve all users
      description: Retrieve information for all registered users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                      description: User's username
                    firstName:
                      type: string
                      description: User's first name
                    lastName:
                      type: string
                      description: User's last name
        '400':
          description: Bad request
        '401':
          description: Invalid token
      security:
        - bearerAuth: []
  /chats/{username}:
    get:
      summary: Retrieve all chats of a user
      description: Retrieve information for all chats of a specified user
      parameters:
        - name: username
          in: path
          required: true
          description: The username of the user whose chats are to be retrieved
          schema:
            type: string
      responses:
        '200':
          description: List of chats
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: Chat id
                    interlocutor:
                      allOf: [$ref: '#/components/schemas/User']
                    messages:
                      type: array
                      items:
                        type: object
                        properties:
                          chatId:
                            type: string
                            description: Chat id that this message belongs to
                          messageId:
                            type: string
                            description: Personal id of the message
                          sender:
                            allOf: [$ref: '#/components/schemas/User']
                          content:
                            type: string
                            description: Message content
                          date:
                            type: string
                            format: date-time
                            description: Date when the message was sent
        '400':
          description: Bad request
        '401':
          description: Invalid token
      security:
        - bearerAuth: []
